[package]
name = "live2d-cubism-core-sys"
authors = ["https://github.com/James2022-rgb"]
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

build = "src/build.rs"

[dependencies]

[build-dependencies]
bindgen = "0.61.0"
